#!/usr/bin/env node
// Builds wordsmith/words.js, the game's dictionary, from the ENABLE word list.
//
//   curl -LO https://raw.githubusercontent.com/dolph/dictionary/master/enable1.txt
//   node wordsmith/tools/build-words.js enable1.txt
//
// ENABLE (Enhanced North American Benchmark LExicon, Alan Beale and M. Cooper) is in the public domain; see
// the README. The input is checked against the sha256 of the copy the shipped words.js was built from, so a
// different or altered list is noticed rather than silently shipped (pass --any to build from it anyway).
//
// The DAWG is built by the game's own code (the logic half of index.html, lifted into vm), packed by the
// game's own packDawg, gzipped, and base64'd into a script that assigns one global. A <script src> works
// over file://, where fetch() of a local file does not, and the service worker caches it like any page file.
'use strict';
const fs = require('fs'), path = require('path'), vm = require('vm'), zlib = require('zlib'), crypto = require('crypto');

const ENABLE_SHA256 = '3f16130220645692ed49c7134e24a18504c2ca55b3c012f7290e3e77c63b1a89';
const src = process.argv[2];
if (!src) { console.error('usage: node build-words.js <enable1.txt> [--any]'); process.exit(2); }
const raw = fs.readFileSync(src);
const sha = crypto.createHash('sha256').update(raw).digest('hex');
if (sha !== ENABLE_SHA256 && !process.argv.includes('--any')) {
  console.error('input sha256 ' + sha + ' is not the ENABLE list words.js was built from (' + ENABLE_SHA256 + '); pass --any to build anyway');
  process.exit(1);
}

const html = fs.readFileSync(path.join(__dirname, '..', 'index.html'), 'utf8');
const logic = html.slice(html.indexOf("'use strict';"), html.indexOf('// ---------- UI ----------'));
const ctx = { console, Math, Map, Set, Uint32Array, Int32Array, Int8Array, Uint8Array, Uint16Array, Array, Object, String, JSON, Number, Error };
ctx.globalThis = ctx; vm.createContext(ctx); vm.runInContext(logic, ctx);
const W = ctx.__ws;

// Words of 2 to 15 letters: nothing longer fits on the board, and a one-letter "word" is never scored.
const words = raw.toString('latin1').split(/\r?\n/).map((w) => w.trim().toUpperCase()).filter((w) => /^[A-Z]{2,15}$/.test(w));
const unique = [...new Set(words)].sort();
const E = W.buildDawg(unique);
const D = W.makeDict(E);
const back = [];
W.allWords(D, (w) => back.push(w));
if (back.length !== unique.length || back.join('\n') !== unique.join('\n')) { console.error('DAWG does not reproduce the list'); process.exit(1); }
const packed = W.packDawg(E);
const gz = zlib.gzipSync(Buffer.from(packed), { level: 9, mtime: 0 });
// The round trip through the game's own decoders, exactly as the page will do it.
const E2 = W.unpackDawg(W.gunzip(W.b64bytes(gz.toString('base64'))));
if (E2.length !== E.length || E2.some((v, i) => v !== E[i])) { console.error('pack/unpack round trip failed'); process.exit(1); }

const check = crypto.createHash('sha256').update(unique.join('\n')).digest('hex');
const out = '/* Wordsmith dictionary. Generated by tools/build-words.js; do not edit by hand.\n'
  + '   Source: ENABLE (Enhanced North American Benchmark LExicon) by Alan Beale and M. Cooper, which is in the\n'
  + '   public domain. enable1.txt sha256 ' + sha + '.\n'
  + '   ' + unique.length + ' words of 2-15 letters, as a DAWG of ' + E.length + ' edges, packed, gzipped and base64-encoded.\n'
  + '   `check` is the sha256 of the words joined by newlines, which test/dict.js recomputes from the DAWG. */\n'
  + 'var WORDSMITH_DICT = { words: ' + unique.length + ', edges: ' + E.length + ', check: \'' + check + '\', gz: \'' + gz.toString('base64') + '\' };\n';
fs.writeFileSync(path.join(__dirname, '..', 'words.js'), out);
console.log('input sha256', sha);
console.log('words', unique.length, 'edges', E.length, 'packed', packed.length, 'gzip', gz.length, 'words.js', out.length);
